"""Parses manually-exported Zoho CRM "Sent Email Status" report files
(XLSX or CSV) into the same canonical NormalizedRow schema used by the
live-API search path (email_log.py), so search/filter/export logic is
fully shared between the two data sources.

Why this exists: the live `Get Emails of a Record` API path for
`user_emails` (mailbox-sync-derived email history — almost certainly
where most of this org's real historical correspondence lives) returns
a `CANNOT_PROCESS` error for this org, a Zoho-side mailbox/IMAP-sync
configuration issue confirmed via live testing and Zoho's own docs, not
something this app can fix. The same underlying data IS available by
manually running the "Sent Email Status" report from Zoho CRM's Reports
section and exporting it (Zoho has no REST API for reading saved report
data directly — confirmed via its own API reference docs). This module
lets one or more such exports be uploaded and searched/filtered/exported
entirely within the app, working around the broken live path.

Confirmed real export layout (captured from three actual exports of this
report): a handful of title/meta rows (report title, "Generated by ...
on ...", a blank row, "Record Count : N", another blank row), then a
header row:

    Sent To | Subject | Sent On | Module | Last Opened | Last Clicked | Bounced Time

"Sent To" is a comma-separated list of "Display Name<email@address>"
entries per row (one row = one email event, potentially multiple
recipients) — the same format the earlier one-off Servicevend script
parsed by hand.
"""

from __future__ import annotations

import csv
import io
import re
from datetime import datetime

import pandas as pd

from email_log import NormalizedRow, merge_and_dedupe

_RECIPIENT_RE = re.compile(r"^(.*?)<([^<>]+)>$")

REQUIRED_HEADERS = ["Sent To", "Subject", "Sent On", "Module"]


class ReportParseError(ValueError):
    """Raised when an uploaded file doesn't look like a Zoho 'Sent Email
    Status' export — e.g. the wrong report was exported, or Zoho changes
    the export's column layout in future."""


def _parse_recipients(cell) -> list[dict]:
    if not cell or not isinstance(cell, str):
        return []
    parts = [p.strip() for p in cell.split(",") if p.strip()]
    out = []
    for part in parts:
        m = _RECIPIENT_RE.match(part)
        if m:
            out.append({"email": m.group(2).strip(), "name": m.group(1).strip()})
        elif "@" in part:
            out.append({"email": part, "name": ""})
    return out


def _coerce_datetime(value) -> datetime | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value
    try:
        parsed = pd.to_datetime(value)
    except (ValueError, TypeError):
        return None
    if pd.isna(parsed):
        return None
    return parsed.to_pydatetime()


def _find_header_row(rows: list[list]) -> int | None:
    """Scan for the row that actually contains 'Sent To' and 'Subject'
    rather than assuming a fixed offset — the number of title/meta rows
    Zoho puts above the header has already varied slightly between
    exports captured for this app."""
    for i, row in enumerate(rows):
        cells = {str(c).strip() for c in row if c is not None}
        if {"Sent To", "Subject"} <= cells:
            return i
    return None


def _rows_from_xlsx(data: bytes) -> list[list]:
    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(data), read_only=True, data_only=True)
    ws = wb.worksheets[0]
    return [list(row) for row in ws.iter_rows(values_only=True)]


def _rows_from_csv(data: bytes) -> list[list]:
    text = data.decode("utf-8-sig", errors="replace")
    return [row for row in csv.reader(io.StringIO(text))]


def parse_report_file(filename: str, data: bytes) -> tuple[list[NormalizedRow], dict]:
    """Parse one uploaded report export into canonical rows.

    Returns (rows, info) — info carries a few stats useful for a sanity
    check in the UI (rows found, rows parsed) without dumping the whole
    file.
    """

    lower = filename.lower()
    if lower.endswith((".xlsx", ".xlsm")):
        raw_rows = _rows_from_xlsx(data)
    elif lower.endswith(".csv"):
        raw_rows = _rows_from_csv(data)
    else:
        raise ReportParseError(
            f"Unsupported file type for '{filename}' — expected .xlsx or .csv."
        )

    header_idx = _find_header_row(raw_rows)
    if header_idx is None:
        raise ReportParseError(
            f"Couldn't find a 'Sent To' / 'Subject' header row in '{filename}'. "
            f"Make sure this is a 'Sent Email Status' report exported from Zoho "
            f"CRM's Reports section."
        )

    header = [str(c).strip() if c is not None else "" for c in raw_rows[header_idx]]
    col_idx = {name: i for i, name in enumerate(header)}

    missing = [c for c in REQUIRED_HEADERS if c not in col_idx]
    if missing:
        raise ReportParseError(
            f"'{filename}' is missing expected column(s): {', '.join(missing)}."
        )

    opened_idx = col_idx.get("Last Opened")
    bounced_idx = col_idx.get("Bounced Time")

    def cell(row, idx):
        if idx is None or idx >= len(row):
            return None
        return row[idx]

    rows: list[NormalizedRow] = []
    data_rows = raw_rows[header_idx + 1 :]
    for raw_row in data_rows:
        if raw_row is None or all(c is None for c in raw_row):
            continue

        recipients = _parse_recipients(cell(raw_row, col_idx["Sent To"]))
        if not recipients:
            continue

        subject = cell(raw_row, col_idx["Subject"]) or ""
        sent_on = _coerce_datetime(cell(raw_row, col_idx["Sent On"]))
        module = cell(raw_row, col_idx["Module"]) or ""

        opened_raw = cell(raw_row, opened_idx) if opened_idx is not None else None
        bounced_raw = cell(raw_row, bounced_idx) if bounced_idx is not None else None
        # Zoho leaves these cells blank ('' or None) when the event didn't
        # happen, and a real timestamp otherwise — a plain truthiness check
        # is enough since a non-empty datetime is always truthy.
        opened = bool(opened_raw) and str(opened_raw).strip() != ""
        bounced = bool(bounced_raw) and str(bounced_raw).strip() != ""

        for r in recipients:
            rows.append(
                NormalizedRow(
                    email_id=None,
                    sent_to=r["email"],
                    sent_to_name=r["name"],
                    subject=str(subject),
                    sent_on=sent_on,
                    direction="sent",
                    status="Bounced" if bounced else ("Opened" if opened else "Sent"),
                    bounced=bounced,
                    opened=opened,
                    source_module=str(module),
                    source_record_id="",
                    source_record_name="",
                )
            )

    info = {
        "filename": filename,
        "data_rows": len(data_rows),
        "parsed_rows": len(rows),
    }
    return rows, info


def parse_report_files(files: list[tuple[str, bytes]]) -> tuple[pd.DataFrame, list[dict]]:
    """Parse and merge multiple uploaded report files into one deduped
    canonical DataFrame. A single bad file doesn't abort the rest — its
    failure is captured in the returned info list under 'error' instead."""

    all_rows: list[NormalizedRow] = []
    infos: list[dict] = []
    for filename, data in files:
        try:
            rows, info = parse_report_file(filename, data)
        except ReportParseError as exc:
            infos.append({"filename": filename, "error": str(exc)})
            continue
        all_rows.extend(rows)
        infos.append(info)

    df = merge_and_dedupe(all_rows)
    return df, infos


def filter_by_address(df: pd.DataFrame, search_value: str, exact: bool) -> pd.DataFrame:
    """Filter an already-merged report DataFrame down to rows matching the
    search value — the report-upload equivalent of search.py's exact/domain
    matching, done locally against already-downloaded data instead of via
    a COQL query."""

    if df.empty:
        return df
    sent_to_lower = df["sent_to"].astype(str).str.lower()
    value = search_value.strip().lower()
    if exact:
        mask = sent_to_lower == value
    else:
        # Domain mode: search_value is normalized to '@domain.com' by the
        # caller, matching search.py's convention.
        mask = sent_to_lower.str.endswith(value)
    return df[mask].reset_index(drop=True)
